### ISSUE TITLE
Outlier volume rejection

### ISSUE THREAD

**Issue by jyeatman** [nipy/dmriprep#19]
QC pipeline should reject bad volumes and write out a QCed dataset (and bvals and bvecs) that has bad volumes (and correspondingm bvecs) removed. We will set suggested thresholds based on maximizing scan rescan reliability. But it would be AWESOME if the plots had sliders on the yaxis where the user could adjust this

**Comment by richford** [comment]
First part of this is resolved by #31. The second part seems redundant with #18. Closing.
