### ISSUE TITLE
Preserve `dim_info`

### ISSUE THREAD

**Issue by arokem** [nipy/dmriprep#35]
The output of dmriprep currently has: 

```
In [7]: hdr = img.header                                                        

In [8]: hdr.get_dim_info()                                                      
Out[8]: (None, None, None)
```

We want to set this to be consistent with the input. See #32

**Comment by richford** [comment]
I believe I can use `header=img.header` to inherit the old header info. However, I'll need to update the `dim` value to reflect that I've dropped some volumes, correct?

@arokem, are there any other fields that I should update.

**Comment by richford** [comment]
@arokem @akeshavan For that matter, we don't know for sure if the input is a Nifti1 image or a Nifti2 image. I should inspect the incoming image and use that type for the output as well, correct?

**Comment by arokem** [comment]
I've only rarely (if ever) seen a Nifti2 in the wild. I am not even
entirely sure what the difference is.
